# In ./grafana/Dockerfile
FROM grafana/grafana:latest

LABEL maintainer="mritunjay <a34mritunjaysingh@gmail.com>"

USER root

# Install any additional plugins if needed
# RUN grafana-cli plugins install grafana-clock-panel

USER grafana