version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile.django
    container_name: projectmanagement
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - django_static:/app/static
    environment:
      - DEBUG=True
      - SECRET_KEY=your_secret_key_here
      - DATABASE_URL=sqlite:///db.sqlite3
    restart: unless-stopped
    networks:
      - web
      - monitoring

  prometheus:
    build:
      context: ./prometheus
      dockerfile: Dockerfile
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped
    networks:
      - monitoring

  grafana:
    build:
      context: ./grafana
      dockerfile: Dockerfile
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    depends_on:
      - prometheus
    networks:
      - monitoring

networks:
  web:
    driver: bridge
  monitoring:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:
  django_static: